### ISSUE TITLE
[question] Why are tests written using python?

### ISSUE THREAD

**Issue by harrysarson** [wraith1995/complex#4]
Hi,

I was investigating using this libary and I came across `tests/testgen-0.18.py` and was wondering if there was a reason for this python file rather than writing the tests directly in elm?

**Comment by wraith1995** [comment]
I used python because I needed a source of truth. Elm has no built in complex number functionality and I wanted to be able to randomly generate tests. If I wanted to randomly generate tests, I need answers. Thus, tests and their answers are generated in python because python can generate the answers.

**Comment by harrysarson** [comment]
@wraith1995 thanks for your reply :) that makes a lot of sense.
